# Generated by Django 5.2.17 on 2026-09-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Hide from the builder without deleting profile history.')),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='CompetencyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_areas', to='taxonomy.role')),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=96, unique=True)),
                ('label', models.CharField(max_length=300)),
                ('help_text', models.TextField(blank=True, help_text='Shown inline in the builder to disambiguate.')),
                ('claim_type', models.CharField(choices=[('activity', 'Activity performed'), ('proficiency', 'Tool or technique proficiency'), ('trait', 'Self-reported disposition')], default='activity', max_length=16)),
                ('seniority_hint', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=16)),
                ('variants', models.JSONField(blank=True, default=list, help_text="Optional version multi-select, e.g. SDTM IG ['3.1.2','3.2','3.3']. Empty list means a plain yes/no claim.")),
                ('source_ref', models.PositiveIntegerField(blank=True, help_text='Item number in the source recruitment breakdown. Traceability only.', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('competency_areas', models.ManyToManyField(related_name='activities', to='taxonomy.competencyarea')),
            ],
            options={
                'ordering': ('sort_order', 'label'),
                'indexes': [models.Index(fields=['claim_type'], name='taxonomy_ac_claim_t_7242c3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='competencyarea',
            constraint=models.UniqueConstraint(fields=('role', 'code'), name='uniq_area_code_per_role'),
        ),
    ]
