# Generated by Django 5.2.17 on 2026-08-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='taxonomy_ac_compete_8a277a_idx',
        ),
        migrations.AddField(
            model_name='activity',
            name='competency_areas',
            field=models.ManyToManyField(related_name='activities', to='taxonomy.competencyarea'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='competency_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_old', to='taxonomy.competencyarea'),
        ),
    ]
