# Generated by Django 5.2.17 on 2026-08-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_remove_activity_taxonomy_ac_compete_8a277a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='competency_area',
        ),
    ]
