# Generated by Django 5.2.17 on 2026-09-01 05:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('location_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2.', max_length=2)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('open_to_opportunities', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=True, help_text='Candidate-controlled. When false the profile is excluded from recruiter search.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuilderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_area_codes', models.JSONField(blank=True, default=list)),
                ('last_area_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='taxonomy.role')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_progress', to='profiles.candidateprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Some exposure'), (2, 'Working knowledge'), (3, 'Proficient'), (4, 'Expert / can lead others')], null=True)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('is_ai_inferred', models.BooleanField(default=False, help_text='True if this claim was automatically extracted from a resume by AI')),
                ('last_used_year', models.PositiveSmallIntegerField(blank=True, help_text='Drives recency decay in match scoring.', null=True)),
                ('variants', models.JSONField(blank=True, default=list, help_text='Subset of Activity.variants the candidate claims.')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='taxonomy.activity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='profiles.candidateprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['activity', 'profile'], name='profiles_ac_activit_3a725a_idx'), models.Index(fields=['profile', 'activity'], name='profiles_ac_profile_848259_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'activity'), name='uniq_claim_per_profile_activity')],
            },
        ),
        migrations.CreateModel(
            name='CandidateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('years_experience', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('is_primary', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='profiles.candidateprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taxonomy.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'role'), name='uniq_role_per_profile')],
            },
        ),
    ]
