# Generated by Django 5.2.17 on 2026-09-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='resumes/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_resumes', to='profiles.candidateprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='taxonomy.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'role'), name='uniq_resume_per_profile_role')],
            },
        ),
    ]
