# Generated by Django 5.2.17 on 2026-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidateprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityclaim',
            name='is_ai_inferred',
            field=models.BooleanField(default=False, help_text='True if this claim was automatically extracted from a resume by AI'),
        ),
    ]
