# Generated by Django 5.2.17 on 2026-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False, help_text='Grants access to candidate search, which reads across the whole pool. Off by default: authentication alone must not open it.'),
        ),
    ]
