import { useState } from 'react';
import { Link } from 'react-router-dom';
import { requestPasswordReset } from '@/lib/api/auth';

export function ForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(''); try { await requestPasswordReset(email); setSent(true); } catch (err: any) { const body = err?.body; setError(body ? Object.values(body).flat().join(' ') : 'Unable to process the request. Please try again.'); } finally { setLoading(false); } }
  return <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-xl"><h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50">Forgot password?</h1><p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">Enter your email and we’ll send a reset link if an account exists.</p>{sent ? <div role="status" className="mt-6 space-y-4"><p className="text-sm">Check your inbox for a password reset link. The link expires shortly.</p><Link to="/login" className="text-blue-600 hover:underline">Return to login</Link></div> : <form onSubmit={submit} className="mt-6 space-y-4">{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<label className="block text-sm font-medium text-zinc-900 dark:text-zinc-300" htmlFor="reset-email">Email</label><input id="reset-email" type="email" required value={email} onChange={e => setEmail(e.target.value)} className="w-full rounded-lg bg-white dark:bg-zinc-900 border border-zinc-300 dark:border-zinc-800 p-2.5 dark:text-zinc-100 dark:placeholder:text-zinc-600" /><button disabled={loading} className="w-full rounded-lg bg-blue-600 py-2.5 font-semibold text-white disabled:opacity-50 hover:bg-blue-700 transition-colors">{loading ? 'Sending...' : 'Send reset link'}</button><Link to="/login" className="block text-center text-sm text-blue-600 dark:text-blue-400 hover:underline">Back to login</Link></form>}</div></div>;
}
