import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { confirmPasswordReset } from '@/lib/api/auth';

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [done, setDone] = useState(false); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); if (password !== confirm) { setError('Passwords do not match.'); return; } const uid = params.get('uid'), token = params.get('token'); if (!uid || !token) { setError('This reset link is invalid or incomplete.'); return; } setLoading(true); try { await confirmPasswordReset({ uid, token, new_password1: password, new_password2: confirm }); setDone(true); setTimeout(() => navigate('/login'), 1500); } catch (err: any) { const body = err.body; setError(body ? Object.values(body).flat().join(' ') : 'This reset link is invalid or expired.'); } finally { setLoading(false); } }
  return <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-xl"><h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50">Set a new password</h1>{done ? <p role="status" className="mt-6 text-sm">Password updated. Redirecting to login...</p> : <form onSubmit={submit} className="mt-6 space-y-4">{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<label className="block text-sm font-medium text-zinc-900 dark:text-zinc-300" htmlFor="new-password">New password</label><input id="new-password" type="password" minLength={8} required value={password} onChange={e => setPassword(e.target.value)} className="w-full rounded-lg bg-white dark:bg-zinc-900 border border-zinc-300 dark:border-zinc-800 p-2.5 dark:text-zinc-100 dark:placeholder:text-zinc-600" /><label className="block text-sm font-medium text-zinc-900 dark:text-zinc-300" htmlFor="confirm-password">Confirm password</label><input id="confirm-password" type="password" minLength={8} required value={confirm} onChange={e => setConfirm(e.target.value)} className="w-full rounded-lg bg-white dark:bg-zinc-900 border border-zinc-300 dark:border-zinc-800 p-2.5 dark:text-zinc-100 dark:placeholder:text-zinc-600" /><button disabled={loading} className="w-full rounded-lg bg-blue-600 py-2.5 font-semibold text-white disabled:opacity-50 hover:bg-blue-700 transition-colors">{loading ? 'Updating...' : 'Update password'}</button><Link to="/login" className="block text-center text-sm text-blue-600 dark:text-blue-400 hover:underline">Back to login</Link></form>}</div></div>;
}
